### ISSUE TITLE
Create a separate routine to calculate content2style ratio

### ISSUE THREAD

**Issue by gabrielelanaro** [gabrielelanaro/ml-prototypes#3]
```
def run_style_transfer(
        self,
        content_img: np.array,
        style_img: np.array,
        num_iterations=1000,
        content_weight=1e3,
        style_weight=1e-2,
    ):
```
`content_weight` and `style_weight` need to be calculated on the fly as they vary according to the image. We need to adjust the weights so that content loss and style loss don't show a difference of orders of magnitude (which happens all the time). To give an example, in my experiments, I was often obliged to set `content_weight=1000` and `style_weight=1`. Ideally, we need to run a couple of dry optimization iterations and compute the content2style ratio, then use it to execute the actual style transfer process. 

As soon as the 2 losses are comparable, then we can add a custom coefficient to let the end-user decide which proportion of content/style he desires.

**ACTION REQUIRED**: we need a separate routine to calculate the content2style ratio

_Originally posted by @FraPochetti in https://github.com/gabrielelanaro/ml-prototypes/pull/1_

**Comment by FraPochetti** [comment]
This is done. Taken care of in this [PR](https://github.com/gabrielelanaro/ml-prototypes/pull/4)
